TugasPPW/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import app_status.urls as app_status
import app_AddFriend.urls as app_addFriend
import app_profile.urls as app_profile
import app_statistic.urls as app_stats
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url="/app_status/", permanent="true"), name='app_status'),
    url(r'^app_status/', include(app_status, namespace='app_status')),
    url(r'^app_addFriend/', include(app_addFriend, namespace='app_addFriend')),
    url(r'^app_profile/', include(app_profile, namespace='profile')),
    url(r'^app_stats/', include(app_stats, namespace='app_stats'))

]

app_AddFriend/urls.py
from django.conf.urls import url
from .views import index, add_friend

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friend', add_friend, name='add_friend')

]

app_profile/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),

 ]

app_statistic/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name='index'),
]

app_status/urls.py
from django.conf.urls import url
from .views import index, status_post
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^status_post', status_post, name='status_post'),
    #url(r'^result_post', message_table, name='result_post'),
]

app_AddFriend/models.py
from django.db import models

# Create your models here.

class Friend(models.Model):
    name = models.CharField(max_length=30)
    URL = models.URLField()
    created_date = models.DateTimeField(auto_now_add=True)
	
    def __str__(self):
	    return self.name

app_profile/models.py
from django.db import models

#DATABASE
class profileMenu(models.Model):
    photo_url = models.URLField(default = "https://i.imgur.com/fy18KSL.jpg");
    name = models.CharField(max_length=234)
    birthday = models.CharField(max_length=100)
    gender = models.CharField(max_length=10)
    description = models.TextField()
    email = models.EmailField()

class Expertise(models.Model):
    user = models.ForeignKey(profileMenu, related_name= "expertises", on_delete= models.CASCADE)
    name = models.CharField(max_length=234)    

app_statistic/models.py
from django.db import models

# Create your models here.

app_status/models.py
from django.db import models

# Create your models here.
class Update(models.Model):
    message = models.CharField(max_length=140)
    created_date = models.DateTimeField(auto_now_add=True)

app_AddFriend/forms.py
from django import forms

class Friend_Form(forms.Form):
    error_messages = {
        'required' : 'Tolong isi input ini',
        'invalid' : 'Isi input ini dengan url',
    }
    attrs = {
        'class' : 'form-control'
    }

    name = forms.CharField(label='Nama', required=True, max_length=30, widget=forms.TextInput(attrs=attrs))
    URL = forms.URLField(required=True, widget=forms.URLInput(attrs=attrs), initial = 'https://')

app_status/forms.py
from django import forms

class Message_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini'
    }
    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Apa yang sedang anda pikirkan ?'
    }

    status = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

# class Comment_Form(forms.Form):
#     error_messages = {
#         'required': 'Tolong isi input ini'
#     }
#     description_attrs = {
#         'type': 'text',
#         'cols': 50,
#         'rows': 4,
#         'class': 'todo-form-textarea',
#         'placeholder':'Masukan Komentar Anda...'
#     }
#     comment = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

app_AddFriend/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import Friend_Form
from .models import Friend
from datetime import datetime

# Create your views here.

def index(request):
    response = {'author': "PaPow"}
    response['friend_form'] = Friend_Form
    friend_dict = Friend.objects.all().values()
    response['friend_dict'] = convert_queryset_into_json(friend_dict)
    html = 'add_friend.html'
    return render(request, html, response)

def add_friend(request):
    form = Friend_Form(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        friend = Friend(name=request.POST['name'], URL=request.POST['URL'])
        friend.save()
        return HttpResponseRedirect('/app_addFriend')
    else:
        return HttpResponseRedirect('/app_addFriend')

def convert_queryset_into_json(queryset):
    ret_val = []
    for data in queryset:
        ret_val.append(data)
    return ret_val

app_profile/views.py
from django.shortcuts import render
from app_profile.models import profileMenu
# Create your views here.

#ngatur fungsi
#response = {'author': "PaPoW"} #TODO Implement yourname
#bio = [{'subject' : 'Birthday', 'value' : '05 Oct'},
      # {'subject' : 'Gender', 'value' : 'Unknown'},
       #{'subject' : 'Expertise', 'value' : 'Django, HTMLL, CSS'},
       #{'subject' : 'Description', 'value' : 'grup tp1 PPW asique'},
       #{'subject' : 'Email', 'value' : 'tp_PaPoW@gmail.com'},
#]
def index(request):
        profile = profileMenu.objects.first()
        expertises = profile.expertises.all()
        html = 'app_profile/app_profile.html'
        response = {
            'profile': profile,
            'expertises': expertises
        }
        return render(request, html, response)

app_statistic/views.py
from django.shortcuts import render
from app_status.models import Update
from app_AddFriend.models import Friend
# Create your views here.

def index(request):
	response = {}
	response['picture'] = "https://i.imgur.com/fy18KSL.jpg"
	response['friends'] = Friend.objects.all().count()
	response['title'] = 'My Stats'
	html = 'app_statistic/app_statistic.html'
	feedCount = Update.objects.all().count()
	response['feed'] = feedCount
	if(feedCount<1):
		response['status'] = 'Tidak ada status'
	else:
		response['status'] = Update.objects.latest('created_date')
	return render(request, html, response)

app_status/views.py
from django.shortcuts import render
from datetime import datetime, date
from .models import Update
from django.http import HttpResponseRedirect
from .forms import Message_Form

response = {'author': "Misael Jonathan"}
curr_year = int(datetime.now().strftime("%Y"))
timeline_status = {}
def index(request):
    response = {}
    response['message_form'] = Message_Form
    message = Update.objects.all()
    response['message'] = message
    response['todo_form'] = Message_Form
    return render(request, 'app_status.html', response)

def status_post(request):
    form = Message_Form(request.POST or None)
    response['message_form'] = Message_Form
    if(request.method == 'POST' and form.is_valid()):
        response['status'] = request.POST['status']
        message = Update(message=response['status'])
        message.save()
        return HttpResponseRedirect('/app_status/')
    else:
        return HttpResponseRedirect('/app_status/')

# def comment_post(request, post):
#     query = Update.objects.get(pk=post)
#     response['comment_form'] = Comment_Form
#     if(request.method == 'POST' and form.is_valid()):
#         response['comment'] = request.POST['comment']
#         comment = Update(message=response['comment'])
#         comment.save()
#         return HttpResponseRedirect('/app_status/')
#     else:
#         return HttpResponseRedirect('/app_status/')

app_AddFriend/templates/add_friend.html
{% extends "base.html" %}

{% block content %}
<content>
  <div class="container">
    <br>
    <br>
    <br>
    <section name="form">
      <h2 class="textcol">Add Friend</h2>
      <form class="textcol" id="form" method="POST" action="{% url 'app_addFriend:add_friend' %}">
        {% csrf_token %}
        {{ friend_form }}
        <br>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    </section>
  </div>

  <div class="container">
    <h3 class="textcol">List Friend</h3>
    {% for friend_data in friend_dict %}
      <div class="textcol">
        <div class="col-md-4 col-xs-4">
          {{ friend_data.name }}
        </div>
        <div class="col-md-4 col-xs-4">
          <a href={{ friend_data.URL}} target="_blank">{{ friend_data.URL }}</a>
        </div>
        <div class="col-md-4 col-xs-4">
          <i>Added {{ friend_data.created_date|date:"d N Y" }} {{ friend_data.created_date|time:"H:i:s" }}</i>
        </div>
      </div>
    {% endfor %}
  </div>
</content>
{% endblock %}

app_AddFriend/templates/layout/bases.html
<!DOCTYPE html>
<style>
.textcol{
    color: white;
  }
</style>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="description" content="Add_Friend">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">

    <title>
      {% block title %} Add Friend {% endblock %}
    </title>
  </head>
  <body style="background-color: #06d6c1">
    <header>
      {% include "header.html" %}
    </header>
    <content>
      <div class="container">
        {% block form %}
          <!-- form goes here -->
        {% endblock %}
      </div>
      <div class="container">
        {% block table %}
          <!-- table goes here -->
        {% endblock %}
      </div>
    </content>
    <br />

      <!-- Jquery n Bootstrap Script -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>

app_profile/templates/app_profile/app_profile.html
{% extends "base.html" %}
{% block content %}

<head>
	<link rel="stylesheet" type="text/css" href="app_profile\static\css\app_profil.css" />
	<style>
	.img-circle {
	border-radius: 50%;
	}
	.buletan{
		text-shadow: 2px 0 0 #fff;
		font-family: Lato;
		border: 2px #802392;
		border-radius: 12px;
	}
	@media only screen and (max-width: 768px) {
  #input-list form {
      width: 350px;
  }
}

</style>
</head>
<body style="background-color:F9C80E;">

<h1 style="color:#124E78;"><b style="font-family: Lato">Profile</b></h1>

<img class="img-circle" src="https://i.imgur.com/fy18KSL.jpg"
alt= "hai" width= 150 height= 150  style= "display: block;
margin-left:auto; margin-right: auto;"	/>

<center>
<h2 style="color:#802392;font-family: Arial;"><strong>{{profile.name}}<strong></h2>
</center>

<table align="center" style= "text-align: left; color:#124E78; font-family: Lato, Arial;" width= "35%">
		<tr><td>Birthday</td> <td>{{profile.birthday}}</td></tr>
		<tr><td>Gender</td> <td>{{profile.gender}}</td></tr>
		<tr><td>Expertise</td> <td class="buletan">{%for expertises in expertises%} {{expertises.name}} {% endfor %}</td></tr>
		<tr><td>Description</td> <td>{{profile.description}}</td></tr>
		<tr><td>Email</td> <td>{{profile.email}}</td></tr>
</table>
</body>

{% endblock %}

app_statistic/templates/app_statistic/app_statistic.html
{% extends "base.html" %}

{% block style %}
	{% load static from staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/app_statistic.css' %}" />
{% endblock %}

{% block content %}
		<div class="content">
			<div>
				<h2><img class="icon" src="https://image.flaticon.com/icons/png/512/172/172175.png" style=";">
				<strong>My Stats</strong></h2>
			</div>
			<hr/>
			<div align="center"><img class="profile-pic" src={{picture}} alt="Profil Picture"></div>
			<section name="user-stats" id="user-stats">
				<div class="flex">
					<div class="flex-item">
						<h3><img src="https://d30y9cdsu7xlg0.cloudfront.net/png/96006-200.png" class="icon" id="friend">: {{friends}} People</h3>
					</div>
					<div class="flex-item">
						<h3><img src="https://cdn3.iconfinder.com/data/icons/social-media-networks-logos-and-badges-1/64/Social__RSS-512.png" class="icon" id="feed">: {{feed}} Post</h3>
					</div>
				</div>
			</section>
			<hr/>
			<div class="latest-post">
				<h3>Latest Post</h3>
				<h4 class="post">
					 {{status.created_date}}<br>
					 {{status.message}}
				</h4>
			</div>
		</div>
{% endblock %}

app_statistic/templates/app_statistic/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="LAB 4">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title> 
        {% block title %} Papow By Imbang{% endblock %}
    </title>
</head>

<body>
    {% include "header.html" %}
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->{{content}}
            {% endblock %}
        </div>

    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "app_statistic/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

app_statistic/templates/app_statistic/partials/footer.html
 <center><p>&copy; {{author}}</p></center>

app_statistic/templates/app_statistic/partials/header.html
<!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'lab-4:index' %}">Home</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <!-- LINK MENUJU table, dan link menuju home#form -->
            <li><a href="{% url 'lab-4:index' %}#form"> Form </a></li>
            <li><a href="{% url 'lab-4:result_table' %}"> Messages Table </a> </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app_status/templates/app_status.html
{% extends "base.html" %}
{% block style %}
    <link rel="stylesheet" type="text/css" href="\static\css\app_status.css"/>
{% endblock %}

{% block content %}
  <!-- <h1> tes hehe</h1> -->
  <div class = "container-judul">
    <h3 id="title" class="main-title">Update Status</h3>
  </div>
  <div class = "big-container">
  <section name="input-list" id="input-list">
    <div class="container">
        <form id="form_isi" method="POST" action="{% url 'app_status:status_post' %}">
            {% csrf_token %}
            {{ message_form }}
            <button class="btn">Post</button>
            <div class="modal">
              <div class="modal__box">
                <p> Apakah anda yakin ingin melakukan post ? </p>
                <p style="font-size: 10px"> Click post untuk melanjutkan </p>
                <p style="font-size: 10px"> Click sekitar untuk membatalkan </p>


                <input id="submit" type="submit" class="btn btn-sm btn-info" value="Submit">
              </div>
            </div>
            <br>
            </form>
            </div>
            </section>
            <section name="timeline" class="timeline" id="timeline">
            <div class="container">
            <div class="flex">
                {% for data in message %}
                  <div class="flex-item">
                      <div class="to-do-list">
                        <div class="col-xs-2" style="padding-top:20px">
                          <img style="display: inline; border-radius: 50%; width: 110px; height: 110px; margin: auto; max-width: 500px;" class="photo" src="http://thumb.ibb.co/gb1pFb/unknown_profile.jpg" alt="unknown_profile" border="0"/>
                        </div>
                        <div class="col-xs-10" style="padding-top:20px">
                          <p class="to-do-list-name">Misael Jonathan</p>
                          <div class="to-do-list-description">
                              {{data.message}}
                          </div>
                          <div class="to-do-list-date-added">
                              {{data.created_date}}
                          </div>
                          </div>
                          </div>
                      </div>
                      <!-- DIBAWAH INI HARUSNYA KOLOM COMMENT HEHE  -->
                      <!-- <div class="flex">
                        <!-- {% if comment %} -->
                          <!-- {% for data in comment %}
                            <div class="flex-item">
                                <div class="to-do-list">
                                    <p class="to-do-list-name">Misael Jonathan</p>
                                    <div class="to-do-list-description">
                                        {{data.message}}
                                    </div>
                                    <div class="to-do-list-date-added">
                                        {{data.created_date}}
                                    </div>
                            {% endfor %} -->
                        <!-- {% else %}
                        <div class="alert alert-danger text-center">
                          <strong>Oops!</strong> Timeline Kosong
                          </div>
                          {% endif %}
                          </div>
                        </div> -->
                  {% endfor %}
    </section>
  </div>
{% endblock %}

{% block javascript %}
    <script type="application/javascript">
    $(function() {
             $('a[href*="#"]:not([href="#"])').click(function() {
               if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
                 var target = $(this.hash);
                 target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
                 if (target.length) {
                   $('html, body').animate({
                     scrollTop: target.offset().top - 55
                   }, 1000);
                   return false;
                 }
               }
             });
           });
{% endblock %}

templates/base.html
<!DOCTYPE html>
<style>
html, body {
    margin: 0;
    height: 100%;
}
content{
   margin:0;
   padding:0;
   min-height:100%;
}
#content {
   min-height:100%;
   position:relative;
}
.textcol{
    color: white;
  }
.footer{
  position: relative;
  height: 50px;
  bottom: 0px;
  width: 100%;
  margin: 0 auto;
  background-color: #efefef;
  text-align: center;
  padding-top: 1px;
}
#footer{
  margin-top: 20px;
}
</style>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="description" content="Papow">
    <meta name="author" content="Team Papow">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    {% block style %}
    {% endblock %}
    <title>Link.Me</title>
  </head>
  <body style="background-color: #05a5ba;">
    <header>
      {% include "header.html" %}
    </header>
    <div id="content">
      {% block content %}
        <!-- content goes here -->
      {% endblock %}
    </div>

    <div class="footer"><h4 id="footer"><strong>&copy; Team Papow</strong></h4>
    </div>

      <!-- Jquery n Bootstrap Script -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      {% block javascript %}
      {% endblock %}
  </body>
</html>

templates/header.html
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Link.Me</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a class="nav-link" href="/app_status/">Status</a></li>
        <li><a class="nav-link" href="/app_profile/">Profile</a></li>
        <li> <a class="nav-link" href="/app_addFriend/">Friends</a></li>
        <li><a class="nav-link" href="/app_stats/">Stats</a></li>
      </ul>
    </div>
  </div>
</nav>